Common Role - Ruby Existence Check
department-of-veterans-affairs/ansible-common-roles pull request #22
Opened 2016-11-04 17:15 UTC by askldjd

This role checks the existence of specific ruby version installed in rbenv. This is part of the effort to create a base AMI that is more reliable and allow for faster deployment.

See also https://github.com/department-of-veterans-affairs/appeals-deployment/issues/179

2016-11-04 17:45 UTC, orischwartz requested changes
LGTM. Can we just get rid of the `skip_ruby` flags? They were a dev setting to save time when targeting local Vagrant instances that already had Ruby. After this PR they'll be obsolete (never used in code, always just passed in via `-e skip_ruby=true`).

2016-11-06 20:16 UTC, askldjd commented
`skip_ruby` flag is removed.

2016-11-07 14:36 UTC, shanear commented
👍 👍 👍

2016-11-07 15:00 UTC, orischwartz approved these changes

2016-11-07 15:00 UTC, merged